### ISSUE TITLE
[CloudSync] Fix importing crash

### ISSUE THREAD

**Issue by nexpid** [nexpid/RevengePlugins#84]
https://discord.com/channels/1205207689832038522/1210989892977557584/1216395378740564008

![Image](https://github.com/nexpid/RevengePlugins/assets/60316309/76e87466-6ad0-4f8b-b6d5-069071edf841)

**Comment by BedBug2479** [comment]
I was going to make a issue for this

glad its already created 🥇

**Comment by nexpid** [comment]
this was already fixed @BedBug2479
make sure you're using this version: https://vendetta.nexpid.xyz/cloud-sync, blame Vendetta for not doing anything
